Repository meldig/SQL, pull requests merged in 2020-11, with the labels that each got.

#91 Intégration recensement
  integration/Recensement_donnees_historiques/TA_RECENSEMENT.sql
  integration/Recensement_donnees_historiques/admin_commune_recensement_historique.sql
  integration/Recensement_donnees_historiques/creation_structure_recensement.sql
  integration/Recensement_donnees_historiques/doc_methodo_recensement_donnees_historique.md
  integration/Recensement_donnees_historiques/format_date.sql
  integration/Recensement_donnees_historiques/import_recensement.bat
  integration/Recensement_donnees_historiques/insertion_nomclature_recensement_donnees_historique.sql
  integration/Recensement_donnees_historiques/insertion_nomenclature_recensement_donnees_historique.sql
  integration/Recensement_donnees_historiques/normalisation_recensement_donnees_historique.sql
  integration/Recensement_donnees_historiques/suppression_table_temporaire_recensement.sql
Labels: Data

#125 Création des commentaires des tables/champs utilisés dans GestionGeo + création d'une vue d'analyse des géométries
  doc/gestiongeo/tables_gestion_geo.tsv
  schema/geogestion/creation_ta_gg_app_adm_rights.sql
  schema/geogestion/creation_ta_gg_doc.sql
  schema/geogestion/creation_ta_gg_dossier.sql
  schema/geogestion/creation_ta_gg_etat.sql
  schema/geogestion/creation_ta_gg_exterieur.sql
  schema/geogestion/creation_ta_gg_famille.sql
  schema/geogestion/creation_ta_gg_files.sql
  schema/geogestion/creation_ta_gg_format.sql
  schema/geogestion/creation_ta_gg_geo.sql
  schema/geogestion/creation_ta_gg_point.sql
  schema/geogestion/creation_ta_gg_source.sql
  schema/geogestion/creation_v_bilan_geom_gestion_geo.sql
Labels: A merger

#128 Création des statistiques des tables GestionGeo
  doc/gestiongeo/statistiques_tables_gestiongeo.tsv
Labels: A merger

#126 Documentation des fonctions dynmap de gestiongeo
  doc/gestiongeo/documentation_interface_gestiongeo.md
  doc/gestiongeo/images_gestiongeo/illustration_2.3.1.PNG
  doc/gestiongeo/images_gestiongeo/illustration_2_1.PNG
  doc/gestiongeo/images_gestiongeo/illustration_2_3_2_1.PNG
  doc/gestiongeo/images_gestiongeo/illustration_2_3_3_2.PNG
  doc/gestiongeo/images_gestiongeo/illustration_2_3_3_2_b.PNG
  doc/gestiongeo/images_gestiongeo/illustration_2_3_4.PNG
Labels: Non intégrable

#127 création de requêtes permettant la maj des statistiques des tables gestiongeo et leur sélection
  analyse/maj_et_selection_statistiques_tables_gestiongeo.sql
  doc/gestiongeo/statistiques_tables_gestiongeo.tsv
Labels: A merger
